### ISSUE TITLE
Permissions error on jetstream install and install npm dependencies

### ISSUE THREAD

**Issue by Gerardlc** [ucan-lab/docker-laravel#146]
On Ubuntu doing jetstream installation when you run "npm run dev" or "make npm-dev":

$ make npm-dev
```
docker compose exec web npm run dev

> dev
> npm run development

glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}

> development
> mix

glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}


Error: EACCES: permission denied, open '/work/backend/public/mix-manifest.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2153:35)
    at File.write (/work/backend/node_modules/laravel-mix/src/File.js:211:12)
    at Manifest.refresh (/work/backend/node_modules/laravel-mix/src/Manifest.js:81:50)
    at /work/backend/node_modules/laravel-mix/src/webpackPlugins/ManifestPlugin.js:21:48
    at Hook.eval [as callAsync] (eval at create (/work/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/work/backend/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.emitAssets (/work/backend/node_modules/webpack/lib/Compiler.js:871:19)
    at /work/backend/node_modules/webpack/lib/Compiler.js:459:10
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/work/backend/public/mix-manifest.json'
}

```

Seems like "/work/backend/" path on docker_compose.yml is not ok?

**Comment by ucan-lab** [comment]
@Gerardlc 
Sorry for the late reply.
The error could not be reproduced in my Mac environment.

It may be a problem due to the difference in the permissions of the files generated on the local side and the container side.

It may be good to align the UID and GID on the local side and the container side.

Although it is a node that was in the web container, we decided to exclude it after v2.0.

This issue will be closed once.
